name: ReleaseCI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Release to S3
      run: bash scripts/pipeline/release.sh "gittyeferson" "Ventas.csv" "AKIAZLM4KFJ7AUNVWC4U" "GoBPrVmtPN8K1H+q7dugwJbYK3K6UB1rXxT/iKNG" "Ventas.csv"